export const ADD_DEVICE = "ADD_DEVICE";
export const LOAD_COMPONENTS_SUCCESS = 'LOAD_COMPONENTS_SUCCESS';
export const LOAD_COMPONENT_SUCCESS = 'LOAD_COMPONENT_SUCCESS';
export const LOAD_DEVICES_SUCCESS = 'LOAD_DEVICES_SUCCESS';
export const LOAD_DEVICE_SUCCESS = 'LOAD_DEVICE_SUCCESS';
